name: Update README

inputs:
  GH_USERNAME:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }}
    required: false
  CONFIG_FILE:
    description: "Path to configuration file"
    default: "./.github/recent-activity.config.yml"
    required: false
on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
